version: 0.0.1

achievements:
  - achievement:
      name: Bug Trackers
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating issues in the project.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count() >= 1
        - trigger:
            actor: author
            action: issue
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Debugging Dynamo
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating useful issues.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count(labels in {'Useful Issue'}) >= 1
        - trigger:
            actor: author
            action: issue
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Pull Request Pioneer
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating pull requests.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count() >= 1
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Merging Master
      icon: "Badge Icon URL Placeholder"
      description: Awarded for getting pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 1
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Merging Wizard
      icon: "Badge Icon URL Placeholder"
      description: Awarded for getting priority pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 1
        - trigger:
            actor: author
            action: pull_request
            condition: count(labels in {'Priority PR'}) >= 1
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Ivy Inspectors
      icon: "Badge Icon URL Placeholder"
      description: Awarded for reviewing pull requests.
      triggers:
        - trigger:
            actor: reviewer
            action: pull_request
            condition: count() >= 1
        - trigger:
            actor: reviewer
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Bug Trackers Bronze
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 5 issues in the project.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count() >= 5
        - trigger:
            actor: author
            action: issue
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Debugging Dynamo Bronze
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 5 useful issues.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count(labels in {'Useful Issue'}) >= 5
        - trigger:
            actor: author
            action: issue
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Pull Request Pioneer Bronze
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 5 pull requests.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count() >= 5
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Merging Master Bronze
      icon: "Badge Icon URL Placeholder"
      description: Awarded for getting 5 pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 5
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Merging Wizard Bronze
      icon: "Badge Icon URL Placeholder"
      description: Awarded for getting 5 priority pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 5
        - trigger:
            actor: author
            action: pull_request
            condition: count(labels in {'Priority PR'}) >= 5
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Ivy Inspectors Bronze
      icon: "Badge Icon URL Placeholder"
      description: Awarded for reviewing 5 pull requests.
      triggers:
        - trigger:
            actor: reviewer
            action: pull_request
            condition: count() >= 5
        - trigger:
            actor: reviewer
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Bug Trackers Silver
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 15 issues in the project.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count() >= 15
        - trigger:
            actor: author
            action: issue
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Debugging Dynamo Silver
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 15 useful issues.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count(labels in {'Useful Issue'}) >= 15
        - trigger:
            actor: author
            action: issue
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Pull Request Pioneer Silver
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 15 pull requests.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count() >= 15
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Merging Master Silver
      icon: "Badge Icon URL Placeholder"
      description: Awarded for getting 15 pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 15
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Merging Wizard Silver
      icon: "Badge Icon URL Placeholder"
      description: Awarded for getting 15 priority pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 15
        - trigger:
            actor: author
            action: pull_request
            condition: count(labels in {'Priority PR'}) >= 15
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Ivy Inspectors Silver
      icon: "Badge Icon URL Placeholder"
      description: Awarded for reviewing 15 pull requests.
      triggers:
        - trigger:
            actor: reviewer
            action: pull_request
            condition: count() >= 15
        - trigger:
            actor: reviewer
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Bug Trackers Gold
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 30 issues in the project.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count() >= 30
        - trigger:
            actor: author
            action: issue
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Debugging Dynamo Gold
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 30 useful issues.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count(labels in {'Useful Issue'}) >= 30
        - trigger:
            actor: author
            action: issue
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Pull Request Pioneer Gold
      icon: "Badge Icon URL Placeholder"
      description: Awarded for creating 30 pull requests.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count() >= 30
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Merging Master Gold
      icon: "Badge Icon URL Placeholder"
      description: Awarded for getting 30 pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 30
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Merging Wizard Gold
      icon: "Badge Icon URL Placeholder"
      description: Awarded for getting 30 priority pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true) >= 30
        - trigger:
            actor: author
            action: pull_request
            condition: count(labels in {'Priority PR'}) >= 30
        - trigger:
            actor: author
            action: pull_request
            condition: created_at >= "2023-12-25"

  - achievement:
      name: Ivy Inspectors Gold
      icon: "Badge Icon URL Placeholder"
      description: Awarded for reviewing 30 pull requests.
      triggers:
        - trigger:
            actor: reviewer
            action: pull_request
            condition: count() >= 30
        - trigger:
            actor: reviewer
            action: pull_request
            condition: created_at >= "2023-12-25"
