name: Branch Protection
on:
  create:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete branch if not created by Ved
        run: |
          if [ "${{ github.actor }}" != "Ved" ]; then
            echo "Only Ved can create branches. Deleting..."
            git push origin --delete "${{ github.ref }}"
          fi
