name: Run CI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: with CI
          repo_token: ${{ secrets.GITHUB_TOKEN }}