name: Build DockerfileGPU

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: [check_labels]
    types: [ completed ]

jobs:
  on-success:

  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3
    - name: Build DockerfileGPU
      run: docker build . --file DockerfileGPU --tag unifyai/ivy:gpu$(date +%s)
