name: Build DockerfileCopsim

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: [ check-labels ]
    types: [ completed ]


jobs:
  on-success:

  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3
    - name: Build DockerfileCopsim
      run: docker build . --file DockerfileCopsim --tag unifyai/ivy:copsim$(date +%s)
