name: Build DockerfileCopsim

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [labeled]
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Label Checker
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'with CI'
    - uses: actions/checkout@v3
    - name: Build DockerfileCopsim
      run: docker build . --file DockerfileCopsim --tag unifyai/ivy:copsim$(date +%s)
