name: Update docs
on:
  workflow_call:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  update-docs:
    name: Update docs
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit
