name: Update docs
on:
  workflow_call:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-docs:
    name: Update docs
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit
