name: failures-message
on:
  workflow_call:
    inputs:
      github_output:
          required: true
          type: string

permissions:
  pull-requests: write

jobs:
  failures-message:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: <!--- CI Output -->

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for this PR, here is the CI results:
            -------------
            ${{ inputs.github_output }}
            <!--- CI Output -->
          edit-mode: replace
