name: intelligent-tests-pr
on:
  workflow_dispatch:
  pull_request:
    types: [ labeled, opened, synchronize, reopened, review_requested ]

permissions:
  actions: read
jobs:
  display_test_results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - run_tests_1
      - run_tests_2
      - run_tests_3
      - run_tests_4
      - run_tests_5
      - run_tests_6
      - run_tests_7
      - run_tests_8
      - run_tests_9
      - run_tests_10
      - run_tests_11
      - run_tests_12
      - run_tests_13
      - run_tests_14
      - run_tests_15
      - run_tests_16
      - run_tests_17
      - run_tests_18
      - run_tests_19
      - run_tests_20
      - run_tests_21
      - run_tests_22
      - run_tests_23
      - run_tests_24
      - run_tests_25
      - run_tests_26
      - run_tests_27
      - run_tests_28
      - run_tests_29
      - run_tests_30
      - run_tests_31
      - run_tests_32
      - run_tests_33
      - run_tests_34
      - run_tests_35
      - run_tests_36
      - run_tests_37
      - run_tests_38
      - run_tests_39
      - run_tests_40

    steps:
      - name: Download all test results
        uses: actions/download-artifact@v3

      - name: Combined Test Results
        run: |
          find . -name "test_results_*.txt" -exec cat {} + > combined_test_results.txt
          echo "Test results summary:"
          cat combined_test_results.txt

      - name: New Failures Introduced
        run: |
          find . -name "new_failures_*.txt" -exec cat {} + > combined_failures.txt
          if [ -s combined_failures.txt ]
          then
              echo "This PR introduces the following new failing tests:"
              cat combined_failures.txt
          else
              echo "This PR does not introduce any new test failures! Yippee!"
          fi

  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
                 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
                 39, 40]
    steps:
      - name: Checkout Ivy 🛎
        uses: actions/checkout@v3
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Determine and Run Tests
        id: tests
        run: |
          git clone -b master${{ matrix.branch }} https://github.com/unifyai/Mapping.git --depth 1
          pip install pydriller
          cp Mapping/tests.pbz2 ivy/
          cd ivy
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          python determine_tests.py extra
          set -o pipefail
          python run_tests_pr.py new_failures_${{ matrix.branch }}.txt | tee test_results_${{ matrix.branch }}.txt
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test_results_${{ matrix.branch }}
          path: ivy/test_results_${{ matrix.branch }}.txt

      - name: Upload New Failures
        uses: actions/upload-artifact@v3
        with:
          name: new_failures_${{ matrix.branch }}
          path: ivy/new_failures_${{ matrix.branch }}.txt

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
