name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  lint:
    uses: unifyai/workflows/.github/workflows/lint.yml@main
    secrets: inherit
