name: lint

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: |
            **/optional*.txt
            **/requirements*.txt
      - name: Install dependencies
        run: |
          python -m pip install flake8
      - name: Analysing the code with Flake8
        run: |
          flake8 $(git ls-files '*.py')
