name: duplicate-tests
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
   run_tests_1:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 100

       - name: Get Job URL
         uses: Tiryoh/gha-jobid-action@v0
         id: jobs
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           job_name: ${{ github.job }}

       - name: Update Mapping and Determine Tests
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         run: |
           source ./ivy/clone_mapping.sh master1
           pip install pydriller pymongo
           cp Mapping/tests.pbz2 ivy/
           cd ivy
           python duplicate_checking.py
