name: Trigger lint format

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  fix-linting:
    name: PR Lint Bot
    uses: NripeshN/workflows/.github/workflows/pr-lint-bot.yml@main
    with:
      COMMIT_MESSAGE: "🤖 Lint code"
    secrets: inherit
