name: Trigger lint format

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  fix-linting:
    name: PR Lint Bot
    uses: NripeshN/workflows/.github/workflows/pr-lint-bot.yml@main
    secrets: inherit