name: gpu_test_on_pr
on: [pull_request]
permissions:
  actions: read

jobs:
  run_tests_gpu:
    runs-on: self-hosted
    steps:
      - name: Clean repository
        run:
          sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - name: Checkout Ivy 🛎
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          set-safe-directory: false

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Run Tests
        id: tests
        run: |
          pip install pymongo
          cd ivy
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          python setup_tests.py '/ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py::test_acos'
          python run_tests.py ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD }} ${{ secrets.MONGODB_PASSWORD }} 'false' 'true' ${{ github.run_id }} ${{ steps.jobs.outputs.html_url }}
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
