name: test-fn-core
on: [push, pull_request]
jobs:
  run-nightly-tests:
    if: ${{ !contains(github.event.pull_request.labels.name), 'Function Reformatting' }}
    strategy:
      matrix:
        backend: [numpy, jax, tensorflow, torch]
        module: [test_creation, test_device, test_dtype, test_elementwise, test_general,
                test_gradients, test_linalg, test_manipulation, test_meta, test_nest,
                test_random, test_set, test_sorting, test_statistical, test_utility]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      - name: Cache hypothesis
        uses: actions/cache@v3
        with:
          path: |
            ivy/.hypothesis
          key: ${{ runner.os }}-hypothesis

      - name: Run Ivy Functional Core Tests
        run: |
          cd ivy
          mkdir -p .hypothesis
          docker run --rm -v `pwd`:/ivy -v `pwd`/.hypothesis:/.hypothesis unifyai/ivy:latest python3 -m pytest --backend ${{ matrix.backend}} ivy/ivy_tests/test_ivy/test_functional/test_core/${{ matrix.module}}.py
