name: test-fn-sorting-torch
on:
  push:
  pull_request:
    types: [labeled]
jobs:
  run-nightly-tests:
    
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: with CI
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      - name: Cache hypothesis
        uses: actions/cache@v3
        with:
          path: |
            ivy/.hypothesis
          key: ${{ runner.os }}-hypothesis

      - name: Run Sorting Tests
        run: |
          cd ivy
          mkdir -p .hypothesis
          docker run --rm -v `pwd`:/ivy -v `pwd`/.hypothesis:/.hypothesis unifyai/ivy:latest python3 -m pytest --backend torch ivy/ivy_tests/test_ivy/test_functional/test_core/test_sorting.py
