name: test-array-api-tensorflow
on:
  push:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  run-tensorflow-array-api-tests:
    
    runs-on: ubuntu-latest
    steps:
      - name: Label Checker
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'with CI'
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-array-api-tensorflow.yml
          name: hypothesis_tensorflow_zip
          path: |
            ivy/.hypothesis/
            
      - name: Unzip Hypothesis Examples
        run: |
          cd ivy/.hypothesis
          unzip examples.zip
          rm examples.zip
          
      - name: Run TensorFlow Tests
        id: tests
        run: |
          cd ivy
          ./test_array_api.sh tensorflow
        continue-on-error: true
        
      - name: Zip Hypothesis Examples
        run: |
          cd ivy/.hypothesis
          zip -r examples.zip examples
          
      - name: Upload hypothesis
        uses: actions/upload-artifact@v3
        with:
          name: hypothesis_tensorflow_zip
          path: |
            ivy/.hypothesis/examples.zip
    
      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
