name: test-array-api-jax
on: [push, pull_request]
jobs:
  run-jax-array-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'
          
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Set hypothesis profile
        run: |
          python3 ivy_tests/set-profile.py

      - name: Cache hypothesis
        uses: actions/cache@v3
        with:
          path: |
            .hypothesis
          key: ${{ runner.os }}-hypothesis

      - name: Run JAX Tests
        run: |
          cd ivy
          ./test_array_api.sh jax
