name: test-docstrings
on: [push, pull_request]
jobs:
  run-docstring-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: with CI
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Run Docstring Tests
        run: |
          cd ivy
          docker run --rm -i -v "$(pwd)":/ivy unifyai/ivy:latest python3 -m pytest ivy/ivy_tests/test_docstrings.py
