name: test-fn-nn
on: [push, pull_request]
jobs:
  run-nightly-tests:
    if: ${{ !contains(github.event.pull_request.labels) }}
    strategy:
      matrix:
        backend: [numpy, jax, tensorflow, torch]
        module: [test_activations, test_layers, test_losses, test_norms]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      - name: Cache hypothesis
        uses: actions/cache@v3
        with:
          path: |
            ivy/.hypothesis
          key: ${{ runner.os }}-hypothesis

      - name: Run Ivy Functional NN Tests
        run: |
          cd ivy
          mkdir -p .hypothesis
          docker run --rm -v `pwd`:/ivy -v `pwd`/.hypothesis:/.hypothesis unifyai/ivy:latest python3 -m pytest --backend ${{ matrix.backend}} ivy/ivy_tests/test_ivy/test_functional/test_nn/${{ matrix.module}}.py
